### ISSUE TITLE
Can`t connect Philips TV

### ISSUE THREAD

**Issue by matrixpsk** [mariusmotea/diyHue#321] opened 2018-08-14 18:06 UTC
Hello @mariusmotea and thanks for great work in this project.
I was try connect my philips tv (42pfs7309) to diyHue, TV find bridge normally, but not responce when I push "Activate" on LinkButton page.
I was listed logs and find this error, when TV wait pressing activate button, this error replay every second:
`Sending M-Search response to 192.168.1.112
Sending M-Search response to 192.168.1.112
192.168.1.108 - - [14/Aug/2018 17:18:40] "GET /hue/linkbutton HTTP/1.1" 200 -
192.168.1.112 - - [14/Aug/2018 17:18:49] "POST /api/ HTTP/1.1" 200 -
in post method
/api/
b'{\n\t"devicetype": "1_42PFS7309/60"\n}\n'
192.168.1.112 - - [14/Aug/2018 17:18:50] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.112 - - [14/Aug/2018 17:18:50] code 400, message Bad request syntax ('{')
192.168.1.112 - - [14/Aug/2018 17:18:50] "{" 400 -
192.168.1.112 - - [14/Aug/2018 17:18:50] "POST /api/ HTTP/1.1" 200 -
in post method
/api/
b'{\n\t"devicetype": "1_42PFS7309/60"\n}\n'
192.168.1.112 - - [14/Aug/2018 17:18:50] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.112 - - [14/Aug/2018 17:18:50] code 400, message Bad request syntax ('{')
192.168.1.112 - - [14/Aug/2018 17:18:50] "{" 400 -
sync with lights
`
What can i do with this problem?

**Comment by mariusmotea** [comment] 2018-08-14 18:32
i believe the issue is generated by the `\n\t`  and `\n` from posted json that made the json to not be valid. I will try to find an workaround for this.

**Comment by mariusmotea** [comment] 2018-08-14 18:54
I made a new commit, can you test it?

**Comment by matrixpsk** [comment] 2018-08-14 19:09
Thanks! If you will need more information, write to me, i will try to help.

**Comment by mariusmotea** [comment] 2018-08-14 19:12
Your info was good because show the possible issue. This commit that i made is just for post request, is possible to ve necessary also for put requests

**Comment by matrixpsk** [comment] 2018-08-14 20:15
I was tested with new commit of HueEmulator3.py, but it still not work. Logs:

`192.168.1.112 - - [14/Aug/2018 20:09:20] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.112 - - [14/Aug/2018 20:09:20] code 400, message Bad request syntax ('{')
192.168.1.112 - - [14/Aug/2018 20:09:20] "{" 400 -
192.168.1.112 - - [14/Aug/2018 20:09:21] "POST /api/ HTTP/1.1" 200 -
in post method
/api/
b'{\n\t"devicetype": "1_42PFS7309/60"\n}\n'
`

**Comment by mariusmotea** [comment] 2018-08-15 06:52
i did not manage to replicate this, for me is working fine:
```
marius@XPS-13:~$ curl https://192.168.10.112/api -X POST -d "$(echo -e '{\n\t"devicetype": "1_42PFS7309/60"\n}\n')" -k 
[{"success":{"username":"c47907abd2a80492ca9388b05c0e3825"}}]

marius@XPS-13:~$ curl https://192.168.10.112/api/c47907abd2a80492ca9388b05c0e3825/config  -k
{"starterkitid":"","dhcp":true,"factorynew":false,"linkbutton":false,"proxyport":0,"bridgeid":"B827EBFFFEC8991C","portalservices":true,"whitelist":{"a7161538be80d40b3de98dece6e91f90":{"last use date":"2018-08-15T00:16:55","create date":"2018-08-11T20:37:04","name":"Hue 3#HTC U11"},"c47907abd2a80492ca9388b05c0e3825":{"last use date":"2018-08-15T09:48:12","create date":"2018-08-15T06:47:02","name":"1_42PFS7309/60"}},"modelid":"BSB002","swupdate":{"notify":true,"updatestate":0,"text":"","url":"","checkforupdate":false,"devicetypes":{"bridge":false,"sensors":[],"lights":[]}},"replacesbridgeid":null,"datastoreversion":"70","ipaddress":"192.168.10.112","timezone":"Europe/Bucharest","internetservices":{"internet":"connected","remoteaccess":"connected","swupdate":"connected","time":"connected"},"mac":"b8:27:eb:c8:99:1c","proxyaddress":"none","portalconnection":"connected","netmask":"255.255.255.0","swupdate2":{"bridge":{"lastinstall":"2018-06-08T19:09:45","state":"noupdates"},"checkforupdate":false,"autoinstall":{"up* Connection #0 to host 192.168.10.112 left intact
datetime":"T14:00:00","on":false},"state":"noupdates","lastchange":"2018-06-09T10:11:08"},"UTC":"2018-08-15T06:48:12","gateway":"192.168.10.1","portalstate":{"outgoing":true,"communication":"disconnected","incoming":false,"signedon":true},"swversion":"1806051111","localtime":"2018-08-15T09:48:12","zigbeechannel":25,"backup":{"errorcode":0,"status":"idle"},"apiversion":"1.24.0","name":"Philips hue"}
```

in the error `code 400, message Bad request syntax ('{')` it is complaining about the curly bracket, but i have no idea why.

**Comment by matrixpsk** [comment] 2018-08-15 08:00
How version of firmware installed on your TV? On my TV version is 012.003.086.128 (latest).
I will search older firmware and test it with my TV, and write results here.

**Comment by mariusmotea** [comment] 2018-08-15 09:30
I test with curl, not with my tv. I have two Philips tv's, 6000 series, one received update to android 7 and i did not test after upgrade. I hope i will have some time to test it today

**Comment by cheesemarathon** [comment] 2018-09-06 19:31
@matrixpsk Are you still having issues?

**Comment by matrixpsk** [comment] 2018-09-08 10:33
I was reinstall raspbian to latest version and install hueEmulator to latest version, test it, and i still have this issue, no changes :(

`192.168.1.111 - - [08/Sep/2018 10:29:57] "POST /api/ HTTP/1.1" 200 -
192.168.1.111 - - [08/Sep/2018 10:29:57] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.111 - - [08/Sep/2018 10:29:57] code 400, message Bad request syntax ('{')
192.168.1.111 - - [08/Sep/2018 10:29:57] "{" 400 -
192.168.1.111 - - [08/Sep/2018 10:29:58] "POST /api/ HTTP/1.1" 200 -
192.168.1.111 - - [08/Sep/2018 10:29:58] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.111 - - [08/Sep/2018 10:29:58] code 400, message Bad request syntax ('{')
192.168.1.111 - - [08/Sep/2018 10:29:58] "{" 400 -`

**Comment by mariusmotea** [comment] 2018-09-08 10:37
Can you upload your config.json file?

**Comment by matrixpsk** [comment] 2018-09-08 10:46
Of course, i was upload it on https://pastebin.com/A0Cc7rQ9

**Comment by mariusmotea** [comment] 2018-09-08 11:00
Config ok, tv was successfully register, i can replicate his GET request with no errors. I still don't understand from were it come the error "Bad request syntax ('{')" so i prepared a script with debug mode enabled. Please replace HueEmulator3.py with following content and don't use webgui or mobile application during the pair process to have just the requests from tv. Then paste here the output ( code formatted )

https://pastebin.com/M9e3xUib

**Comment by matrixpsk** [comment] 2018-09-09 19:36
Nothing new, i think..

`pi@raspberrypi:/opt/hue-emulator $ sudo ./HueEmulator3.py
2018-09-09 19:30:00,579 - root - DEBUG - b827ebd36c48
2018-09-09 19:30:00,585 - root - DEBUG - Config loaded
2018-09-09 19:30:00,590 - root - DEBUG - starting ssdp...
2018-09-09 19:30:00,592 - root - DEBUG - start ssdp broadcast
2018-09-09 19:30:00,596 - root - DEBUG - sync with lights
2018-09-09 19:30:00,598 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 707, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light])
TypeError: get_light_state() missing 1 required positional argument: 'light'
2018-09-09 19:30:00,611 - root - DEBUG - Starting httpd...
2018-09-09 19:30:00,618 - root - DEBUG - Starting ssl httpd...
2018-09-09 19:30:40,954 - root - DEBUG - Sending M-Search response to 192.168.1.111
2018-09-09 19:30:42,764 - root - DEBUG - Sending M-Search response to 192.168.1.111
2018-09-09 19:30:44,072 - root - DEBUG - Sending M-Search response to 192.168.1.111
2018-09-09 19:30:45,481 - root - DEBUG - Sending M-Search response to 192.168.1.111
192.168.1.111 - - [09/Sep/2018 19:31:14] "POST /api/ HTTP/1.1" 200 -
2018-09-09 19:31:14,173 - root - DEBUG - in post method
2018-09-09 19:31:14,175 - root - DEBUG - /api/
2018-09-09 19:31:14,178 - root - DEBUG - b'{\n\t"devicetype": "1_42PFS7309/60"\n}\n'
192.168.1.111 - - [09/Sep/2018 19:31:14] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.111 - - [09/Sep/2018 19:31:14] code 400, message Bad request syntax ('{')
192.168.1.111 - - [09/Sep/2018 19:31:14] "{" 400 -
192.168.1.111 - - [09/Sep/2018 19:31:15] "POST /api/ HTTP/1.1" 200 -
2018-09-09 19:31:15,172 - root - DEBUG - in post method
2018-09-09 19:31:15,173 - root - DEBUG - /api/
2018-09-09 19:31:15,174 - root - DEBUG - b'{\n\t"devicetype": "1_42PFS7309/60"\n}\n'
192.168.1.111 - - [09/Sep/2018 19:31:15] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.111 - - [09/Sep/2018 19:31:15] code 400, message Bad request syntax ('{')
192.168.1.111 - - [09/Sep/2018 19:31:15] "{" 400 -
2018-09-09 19:31:15,708 - root - DEBUG - sync with lights
2018-09-09 19:31:15,709 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 707, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light])
TypeError: get_light_state() missing 1 required positional argument: 'light'
192.168.1.111 - - [09/Sep/2018 19:31:16] "POST /api/ HTTP/1.1" 200 -
2018-09-09 19:31:16,161 - root - DEBUG - in post method
2018-09-09 19:31:16,163 - root - DEBUG - /api/
2018-09-09 19:31:16,164 - root - DEBUG - b'{\n\t"devicetype": "1_42PFS7309/60"\n}\n'
192.168.1.111 - - [09/Sep/2018 19:31:16] "GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1" 200 -
192.168.1.111 - - [09/Sep/2018 19:31:16] code 400, message Bad request syntax ('{')
192.168.1.111 - - [09/Sep/2018 19:31:16] "{" 400 -`

**Comment by cheesemarathon** [comment] 2018-09-12 11:45
@mariusmotea Does the above debug help to solve this at all?

**Comment by mariusmotea** [comment] 2018-09-12 13:54
I believe the issue is related to [this one](https://github.com/samuelclay/NewsBlur/issues/642).

@matrixpsk can you test `ssl_context='adhoc'`

i believe the line
`httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)`
must be:
`httpd.socket = ctx.wrap_socket(httpd.socket, ssl_context='adhoc', server_side=True)`

**Comment by matrixpsk** [comment] 2018-09-12 21:04
> @matrixpsk can you test `ssl_context='adhoc'`

I was test it, result in debug:
`root@raspberrypi:/opt/hue-emulator# ./HueEmulator3.py
2018-09-12 21:02:24,926 - root - DEBUG - b827ebd36c48
2018-09-12 21:02:24,932 - root - DEBUG - Config loaded
2018-09-12 21:02:24,938 - root - DEBUG - starting ssdp...
2018-09-12 21:02:24,940 - root - DEBUG - start ssdp broadcast
2018-09-12 21:02:24,944 - root - DEBUG - sync with lights
2018-09-12 21:02:24,946 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 707, in syncWithLights
    light_state = protocol.get_light_state(bridge_config["lights_address"][light])
TypeError: get_light_state() missing 1 required positional argument: 'light'
2018-09-12 21:02:24,957 - root - DEBUG - Starting httpd...
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1582, in run
    httpd.socket = ctx.wrap_socket(httpd.socket, ssl_context='adhoc', server_side=True)
TypeError: wrap_socket() got an unexpected keyword argument 'ssl_context'
`

**Comment by davidramiro** [comment] 2018-09-16 16:58
Just wanted to chime in and confirm that I get the same code 400 response on my Philips TV (48PFK6959). Clean installation of the latest raspbian. I can help with debugging if needed.

Other than that, diyHue is working perfectly. Thanks for your effort.

**Comment by cheesemarathon** [comment] 2018-09-28 11:47
@mariusmotea Have you got any further on solving this issue?

**Comment by mariusmotea** [comment] 2018-09-28 21:04
Maybe it can be solved with tcpdump if @matrixpsk or anybody else with this problem is able to provide it.

**Comment by jamescdcarter** [comment] 2018-09-29 16:40
Hey, I believe I have the same issue. I have a Phillips 50PUS6272/05 and I am unable to get it to pair with the Hue emulator bridge.

Running it in debug mode shows the following message over and over:

`2018-09-29 16:35:14,380 - root - DEBUG - Sending M-Search response to 192.168.0.60` 

The debug log doesn't show anything other than that message (even when pressing the Hue link button on the web server.

I am running the latest version on a Pi 2 B+ running Raspbian Stretch Lite.

I see you mentioned a tcpdump may help. Could you please give me some instructions on how to produce this and I will be glad to help out!

**Comment by mariusmotea** [comment] 2018-09-29 16:56
I have the same problem with my tv, after last android update it did not detect the emulated bridge. Maybe the mac address of the emulator must be like the ones on original bridges.

**Comment by mariusmotea** [comment] 2018-09-29 17:00
Sorry, after new retry it detectand the emulated bridge and successfuly pair with my tv. I have 43PUS6412/12 with Android 7.0

**Comment by jamescdcarter** [comment] 2018-09-29 17:06
Thanks for replying so quickly!

My TV doesn't run Android, it's some sort of Linux distro.

Is there anything I can do to give you meow information?

**Comment by mariusmotea** [comment] 2018-09-29 17:12
I suggest to perform more retries. In my case i believe i tried 10 times, every time it reply quick that it did not detect any bridges. I write that comment and before to exit setting menu on tv i tried one more time. This time the scanning completed in about 10 seconds and the bridge emulator was detected.

**Comment by jamescdcarter** [comment] 2018-09-29 17:16
Thanks for the advice, I'll give it a go when I get home.

Did you press the Activate button on the Web server when searching?

**Comment by jamescdcarter** [comment] 2018-09-29 21:53
Hey, I've given it a go. Repeating the scan many times and it still won't find the bridge emulator. It tries to scan for around 10 seconds before giving up. I've assigned the emulator and TV static IP addresses, both are connected via ethernet.

Do you have any advice? Thanks

**Comment by mariusmotea** [comment] 2018-09-30 08:06
First be sure the tv send ssdp search messages in your network. For this you need to see in debug output the ssdp search from tv ip address. Some users had issues because some routers filter ssdp protocol and solved this by replacing the router. If you see ssdp messages from tv ip and nothing else then try to replace the mac address of hue emulator device to start with 00:17:88 because this is the prefix for hue bridges.

**Comment by jamescdcarter** [comment] 2018-09-30 08:58
In the debug it is showing that the bridge is sending a response to the TV but nothing shows a request coming in.

`Sending M-Search response to 192.168.0.60`

If it's sending a response, surely the TV is sending a request to the bridge? 

I'll try changing the mac of the bridge and get back to you. Thanks again for your help.

**Comment by mariusmotea** [comment] 2018-09-30 09:45
@jamescdcarter the device where you run the hue emulator use multiple interfaces? Maybe the hue emulator script don't pick the mac address from one interface that don't belong to main interface. You can check this with:

`curl https://127.0.0.1/api/nouser -v -k` look in certificate CN and serial number if it has the mac address of the main interface (you can paste here if you don't understand it + `ip a` command output). Also if you change the mac address of the device you will need to generate new certificate with CN from new mac address.

**Comment by jamescdcarter** [comment] 2018-09-30 09:51
`*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=001d43fffee01b58
*  start date: Sep 29 11:57:50 2018 GMT
*  expire date: Oct 29 11:57:50 2018 GMT
*  issuer: C=NL; O=Philips Hue; CN=001d43fffee01b58
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx 
< Date: Sun, 30 Sep 2018 09:48:28 GMT
< Content-type: application/json
< Content-Length: 227
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
{"factorynew":false,"mac":"00:17:88:f7:83:af","bridgeid":"001788FFFEF783AF","modelid":"BSB002","swversion":"1806051111","apiversion":"1.24.0","name":"Philips hue","starterkitid":"","datastoreversion":70,"replacesbridgeid":null}`

The MAC address is the same as the newly generated one. How do I generate a new certificate?

Here's the output of ip a:

`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:17:88:f7:83:af brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.50/24 brd 192.168.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::3d12:89e8:81de:b75b/64 scope link 
       valid_lft forever preferred_lft forever
`

I did have a wireless adaptor on the pi but I have removed it. It's worth noting my Yeelights have all paired successfully with the bridge, it's just the TV that is causing issues.

**Comment by mariusmotea** [comment] 2018-09-30 10:36
looks ok, but once you changed the mac address you need to change also the certificate. Please note that Hue app cache the old certificate so you will need to wipe app data and pair it again.

`subject: C=NL; O=Philips Hue; CN=001d43fffee01b58`
`"mac":"00:17:88:f7:83:af","bridgeid":"001788FFFEF783AF"`

the CN must be identical with bridgeid (except uppercase characters)

The most easy way to get new cert is with following commands:
```
curl "http://mariusmotea.go.ro:9002/gencert?mac=00:17:88:f7:83:af" > /tmp/cert.pem
sudo mv /tmp/cert.pem /opt/hue-emulator
```

**Comment by mariusmotea** [comment] 2018-09-30 10:39
BTW if you have tcpdump, can you see any tcp connections to https://www.meethue.com/?
The coud based detection send an https request to https://www.meethue.com/api/nupnp that must return an json with local hue bridge details.

**Comment by jamescdcarter** [comment] 2018-09-30 10:52
Thanks for your help. I've generated a new certificate and the CN is the same as the bridgeid.

I'm not too sure how to watch for connections to that domain. `sudo tcpdump -n host www.meethue.com -v` doesn't seem to return anything.

**Comment by mariusmotea** [comment] 2018-09-30 11:06
cut tv internet connection? maybe if it detect there is no internet connection will rely on local ssdp search. I believe there is still no detection even with mac address replaced?

**Comment by jamescdcarter** [comment] 2018-09-30 11:13
After blocking internet connection to the TV I now get this in the debug output:

`----------------------------------------
2018-09-30 11:12:37,839 - root - DEBUG - Sending M-Search response to 192.168.0.60
192.168.0.60 - - [30/Sep/2018 11:12:37] "GET /description.xml HTTP/1.1" 200 -
192.168.0.60 - - [30/Sep/2018 11:12:41] "GET /description.xml HTTP/1.1" 200 -
192.168.0.60 - - [30/Sep/2018 11:12:43] "GET /description.xml HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.60', 37326)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
`

**Comment by mariusmotea** [comment] 2018-09-30 11:39
this is a progress ssdp detection completed, it request the device details with `GET /description.xml` but somehow the connection is reset by  the TV. i believe he don't like something but i don't have idea what. Another alternative is to put nginx as frontend on hue emulator device with configs from original hue bridges that we have.

sterps are:
 1. get nginx conf from here:
https://github.com/mariusmotea/diyHue/tree/bf0296fbe9784743f1bf23207cc378fbdddf5a5f/BridgeEmulator/nginx
 2. split cert.pem intro public.crt and private.key (just copy the right part into these files)
 3. disable https and change http port in HueEmulator3.py file. This is done in the bottom of the script , like in this commit https://github.com/mariusmotea/diyHue/commit/5482277d3572816b3c3f285e1978abc404588d41#diff-1b10137c36e6d146dc0dd0cdab499229

If you don't understand one step just ask.

**Comment by jamescdcarter** [comment] 2018-09-30 11:50
Where do I put the `ngnix.conf` file?

**Comment by mariusmotea** [comment] 2018-09-30 15:12
first install nginx with apt install nginx, then place both config files in /etc/nginx/

**Comment by jamescdcarter** [comment] 2018-09-30 18:46
I tried doing exactly that. The Hue app cannot detect the bridge anymore and the TV is also unable to connect.

**Comment by jamescdcarter** [comment] 2018-09-30 21:00
Awesome, I've sent you a message on Slack :+1:

**Comment by jmac83** [comment] 2018-10-04 05:56
Hi I also experience this issue. I did a little analysis and seems that the tv doesn't follow http protocol.
This is the communication I was able to capture between the tv and the bridge emulator:

`GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1
Host: 192.168.1.102
Accept: */*
Content-Length: 36
Content-Type: application/x-www-form-urlencoded

{
	"devicetype": "1_47PFS7509/12"
}
HTTP/1.1 200 OK
Server: nginx 
Date: Thu, 04 Oct 2018 05:33:05 GMT
Content-type: application/json
Content-Length: 1510

{"bridgeid":"B827EBFFFEDBD077","starterkitid":"","ipaddress":"192.168.1.102","swversion":"1806051111","linkbutton":false,"gateway":"192.168.1.1","apiversion":"1.24.0","replacesbridgeid":null,"backup":{"status":"idle","errorcode":0},"UTC":"2018-10-04T05:33:05","whitelist":{"470a0c52e89555f73b11904c84af6192":{"create date":"2018-10-02T06:31:26","name":"hueHello#deviceName_xyz","last use date":"2018-10-04T05:18:50"},"a7161538be80d40b3de98dece6e91f90":{"create date":"2018-10-03T20:01:32","name":"HueSwitcher#LG-H930","last use date":"2018-10-03T20:41:39"},"c47907abd2a80492ca9388b05c0e3825":{"create date":"2018-10-04T05:33:05","name":"1_47PFS7509/12","last use date":"2018-10-04T05:33:05"},"web-ui-63342":{"create date":"2018-10-01T16:25:58","name":"WegGui User","last use date":"2018-10-03T18:53:12"}},"factorynew":false,"netmask":"255.255.255.0","swupdate2":{"checkforupdate":true},"portalconnection":"connected","datastoreversion":"70","dhcp":true,"name":"Philips hue","proxyport":0,"zigbeechannel":25,"timezone":"Europe/Bucharest","swupdate":{"url":"","text":"","notify":true,"updatestate":0,"checkforupdate":false,"devicetypes":{"bridge":false,"sensors":[],"lights":[]}},"portalstate":{"outgoing":true,"incoming":false,"communication":"disconnected","signedon":true},"proxyaddress":"none","internetservices":{"time":"connected","swupdate":"connected","internet":"connected","remoteaccess":"connected"},"portalservices":true,"localtime":"2018-10-04T05:33:05","mac":"b8:27:eb:db:d0:77","modelid":"BSB002"}<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 400</p>
        <p>Message: Bad request syntax ('{').</p>
        <p>Error code explanation: HTTPStatus.BAD_REQUEST - Bad request syntax or unsupported method.</p>
    </body>
</html>
`

What it looks to me is that firstly the tv calls  
`GET /api/c47907abd2a80492ca9388b05c0e3825/config HTTP/1.1`
then gets the response from the tv, and then instead of normal http call it simply puts following json data into the network socket:
`{
	"devicetype": "1_47PFS7509/12"
}`

This is not expected by the http server therefore we get the following error `Message: Bad request syntax ('{')`

**Comment by cheesemarathon** [comment] 2018-10-05 14:03
@mariusmotea Is this an exception we can code for in the http server?

**Comment by mariusmotea** [comment] 2018-10-05 16:17
I'm still trying to figure what may be the problem here. I believe there is a non standard request that original bridge somehow is handle.

**Comment by jmac83** [comment] 2018-10-05 18:09
Yes it is a non-standard request. Its a GET request with Content-Length header and request body. Basically PUT/POST like GET request.
I did some more investigation of the problem. And it looks like this:
TV calls POST /api and then GET /api/c47907abd2a80492ca9388b05c0e3825/config.
Both request have Content-Length header and both have request body that is json with devicetype.
I did small modification of do_GET function, so that it consumes the request body and ignore sit but the tv still wouldn't pair. 
` ...
   def do_GET(self):
        data_string = b"{}" if self.headers['Content-Length'] is None or self.headers['Content-Length'] == '0' else self.rfile.read(int(self.headers['Content-Length']))
..
            `

Now there is no error just the configuration is passed to the tv but still calls calls both http calls one after another and never pairs....

[http_communication_after_fix.txt](https://github.com/mariusmotea/diyHue/files/2451649/http_communication_after_fix.txt)

**Comment by mariusmotea** [comment] 2018-10-05 18:53
The POST request is done to create the user. It is successful because the GET command contain the username (the long hash in url). I don't understand why you have lot of `{"1":{"devicetype":"1_47PFS7509/12"},"49":{"devicetype":"1_47PFS7509/12"}` in atached config. Looks to be in the root of the json and there must be no just config, lights, groups, scenes, rules, sensors and resourcelinks keys.  Looks like the username was not added in config=>whitelist but in the root on configuration.

**Comment by jmac83** [comment] 2018-10-05 19:11
hmm, I suspect that  multiple entries are result of many pairing attempts...

**Comment by mariusmotea** [comment] 2018-10-05 19:32
i believe what you are doing is to store the posted json in configuration intro an incremental string key. I believe there are two options:
1 .The GET request even with body need to be processed like regular GET request (now it generate the error because of the body)
2. The GET request with body need to be processed as POST request. This means that on GET with body `{"devicetype":"1_47PFS7509/12"}` we don't need to reply the username like in the case of POST request. 

I have the feeling you tried the option 1 and go forward because it did not work. For option 2 you don't need to store anything, just perform same operation with following code:
```
if self.path.startswith("/api") and "devicetype" in post_dictionary: #new registration by linkbutton
            if int(bridge_config["linkbutton"]["lastlinkbuttonpushed"])+30 >= int(datetime.now().strftime("%s")) or bridge_config["config"]["linkbutton"]:
                username = hashlib.new('ripemd160', post_dictionary["devicetype"][0].encode('utf-8')).hexdigest()[:32]
                bridge_config["config"]["whitelist"][username] = {"last use date": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),"create date": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),"name": post_dictionary["devicetype"]}
                response = [{"success": {"username": username}}]
                if "generateclientkey" in post_dictionary and post_dictionary["generateclientkey"]:
                    response[0]["success"]["clientkey"] = "321c0c2ebfa7361e55491095b2f5f9db"
                self._set_end_headers(bytes(json.dumps(response,separators=(',', ':')), "utf8"))
                logging.debug(json.dumps(response, sort_keys=True, indent=4, separators=(',', ': ')))
```

Question is it all GET requests are send as POST, or only the one after pairing.

**Comment by jmac83** [comment] 2018-10-09 16:46
I was able to do pair with the tv finally. Apart from consuming the GET body "linkbutton" flag needs to be set to true when the tv requests the configuration. I've created a pull request with a fix.

**Comment by mariusmotea** [comment] 2018-10-09 20:28
I merge the PR, hope now this issue is solved for everybody.

Thanks for support.

**Comment by cheesemarathon** [comment] 2018-10-11 12:21
Closing this issue as a PR has been merged fixing this issue. If anyone still has problems, please feel free to re-open or create a new issue referencing this one.

**Closed by cheesemarathon** 2018-10-11 12:21 UTC
Labels: bug
