### ISSUE TITLE
Lights don't respond all together like it happens with Hue bridge

### ISSUE THREAD

**Issue by FezVrasta** [mariusmotea/diyHue#224] opened 2018-05-13 10:09 UTC
So, this is kinda annoying, basically if you change color to the lights of a room, they will change color one by one instead of all together.

[Small video to demo the problem](https://i.imgur.com/RGWJoSc.gifv)
(in the video, I was changing the color of the whole room using the Hue app)

I think the problem is that diyHue is not using the "light group" exposed by DeCONZ, but instead it's controlling all the single entities singularly.

**Comment by mariusmotea** [comment] 2018-05-13 10:52
Yes, only the lights are imported, not the groups, Here the issue is that zigbee communication is not that fast, deconz receive the messages instant, but forwarding them to the lights take some time. Now comparing the video with what i have in my living room i see a bigger delay. In most of the cases my lights (just two) are changing in most of the cases instant and even when there are delays they are not that big. ZigBee protocol use 2.4ghz frequency and because is low power it get very easy jammed by wifi. Try to switch the zigbee channel according to [this article](https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence)

**Comment by mariusmotea** [comment] 2018-05-13 10:58
here is a [video](https://www.youtube.com/watch?v=65znu_52ZR4) with my lights. DiyHue receive the remote button event on websocket and apply the rule (on/off)

**Comment by FezVrasta** [comment] 2018-05-13 11:09
Thanks, this is unfortunate, is there any reason of why can't you use the groups somehow?

I think you could detect if all the lights of a given group are being operated, and instead of forwarding the commands to them, group the commands into one that goes directly to the DeCONZ group?

Anyway, these are the wifi channels detected from my home:
![image](https://user-images.githubusercontent.com/5382443/39966586-c5885d56-56ae-11e8-88b6-cac49278a463.png)

I have the ZigBee channel set to 15, which should be good right?

**Comment by mariusmotea** [comment] 2018-05-13 11:16
Not exactly, because there are interference from near wifi channels. Better perform tests, try also channel 25. I remember i had no issues when i change the channel, all devices join automatically to the new channel

**Comment by FezVrasta** [comment] 2018-05-13 11:44
I tried all the channels but the lights are still very laggy.. Especially once paired with my Ambilight, they basically don't change color or change after one minute :-(

**Comment by FezVrasta** [comment] 2018-05-13 11:54
I'm not sure if it's related but I see a lot of 

```
sync with lights
Sending M-Search response to 10.0.0.17
----------------------------------------
Exception happened during processing of request from ('10.0.0.19', 59242)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
```

**Comment by mariusmotea** [comment] 2018-05-13 12:43
Need to see more output, here i don't have the request to the light. In case of timeouts is normal to have these delays. Deconz is on same host with diyhue?

**Comment by FezVrasta** [comment] 2018-05-13 12:48
Yes, same host.


```
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:40] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:40] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:41] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:42] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:42] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:46] "GET /api/243b9a9757506e2e54dfbc10fc0e699f HTT
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:46] "GET /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:46] "GET /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:47] "GET /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: Traceback (most recent call last):
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.finish_request(request, client_address)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.RequestHandlerClass(request, client_address, self)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.handle()
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/http/server.py", line 422, in handle
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.handle_one_request()
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.raw_requestline = self.rfile.readline(65537)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socket.py", line 576, in readinto
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     return self._sock.recv_into(b)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: ConnectionResetError: [Errno 104] Connection reset by peer
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:47] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:47] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:47] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:48] "PUT /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:48] "GET /api/243b9a9757506e2e54dfbc10fc0e699f HTT
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:48] "GET /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:48] "GET /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: 10.0.0.20 - - [13/May/2018 12:26:49] "GET /api/243b9a9757506e2e54dfbc10fc0e699f/lig
May 13 12:26:49 raspberrypi HueEmulator3.py[607]: Traceback (most recent call last):
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.finish_request(request, client_address)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.RequestHandlerClass(request, client_address, self)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.handle()
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/http/server.py", line 422, in handle
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.handle_one_request()
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     self.raw_requestline = self.rfile.readline(65537)
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:   File "/usr/lib/python3.5/socket.py", line 576, in readinto
May 13 12:26:49 raspberrypi HueEmulator3.py[607]:     return self._sock.recv_into(b)
May 13 12:27:02 raspberrypi HueEmulator3.py[607]: in PUT method
May 13 12:27:02 raspberrypi HueEmulator3.py[607]: /api/243b9a9757506e2e54dfbc10fc0e699f/lights/7/state
May 13 12:27:02 raspberrypi HueEmulator3.py[607]: b'{"xy":[0.313,0.329],"bri":255}'
May 13 12:27:02 raspberrypi HueEmulator3.py[607]: Sending M-Search response to 10.0.0.20
May 13 12:27:02 raspberrypi HueEmulator3.py[607]: LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/11/state
May 13 12:27:02 raspberrypi HueEmulator3.py[607]: [
```

More output.

**Comment by mariusmotea** [comment] 2018-05-13 15:08
i'm still not sure, you can try to disable homeassistant to be sure the errors are not generated by this. I believe the best test will be with curl to send PUT requests directly to deconz and check in how much time the light will change his color.

**Comment by FezVrasta** [comment] 2018-05-14 12:32
If I control the lights via the app, or via DeCONZ, or via Home Assistant, they work great.

The problem raises when I try to control a whole room, or when I try to use Ambilight (with Ambilight is really terrible, but I wonder if it's just my TV that's crappy?)

**Comment by mariusmotea** [comment] 2018-05-14 13:07
Ok, you can try a workaround. Some time ago i revert the way groups requests are sent, previews was all in almost same time, now it is waiting for http request to complete in order to go to the next light. I made this because some users have 7-10 lights in a group, and if most of the lights are managed by same device, that device get overloaded when it receive all requests at once. 
In current HueEmulator3.py script you have this code at line 1533 (last version)
```
                        for light in bridge_config["groups"][url_pices[4]]["lights"]:
                            bridge_config["lights"][light]["state"].update(put_dictionary)
                            sendLightRequest(light, put_dictionary)
```

replace `sendLightRequest(light, put_dictionary)` with `Thread(target=sendLightRequest, args=[light, put_dictionary]).start()`. This way will not wait for http to complete, but jump directly to next one in new thread. If deconz get overloaded just add and extra line sleep(0.2), tune the sleep value to minimum but stable possible.

Ambilight i believe is managing individual lights, not the entire group, you can check this by starting the script manually, just look if PUT requests are made on /groups/ or /lights/.

Out of topic, i saw you are UI specialist, maybe you can help me with some suggestions to #226, i want to create an interface for groups that allow on/off and brightness control (something basic).

Marius.

**Comment by FezVrasta** [comment] 2018-05-14 13:34
Thanks for the tips, I'd rather have the emulator use the groups whenever possible, why isn't this supported? Is there any limitation?

Anyway, I commented on #226

**Comment by mariusmotea** [comment] 2018-05-14 14:21
Is not yet implemented because the emulator need to be a little more smarter and what stopped me is the limitation to store the scenes with different colors per light (ex: default scenes in hue app). By implementing this future all lights in deconz group will be like one. Now i'm thinking it is possible to import the groups as lights, so one group will be one light. This way the lights will react in the same time, but will not be possible to control them individually. Second bad think is the impossibility to create groups without to sacrifice remotes. In hue emulator you can do more with ikea and xiaomi sensors, than with deconz.

**Comment by cheesemarathon** [comment] 2018-08-29 15:37
@mariusmotea and @FezVrasta what do we think the status of this issue is?

**Comment by FezVrasta** [comment] 2018-08-29 15:43
I'm not sure, it improved but it's yet not optimal.

**Comment by cheesemarathon** [comment] 2018-08-31 07:32
Ok, I'm going to close this issue for now but I have added it to the Suggested Enhancements project board so it can be improved further in the future.

**Closed by cheesemarathon** 2018-08-31 07:32 UTC
Labels: bug
