### ISSUE TITLE
Python Cleanup

### ISSUE THREAD

**Issue by titilambert** [mariusmotea/diyHue#262] opened 2018-06-16 15:25 UTC
Hello !
I just found your project, and this is really awesome !
The only issue is the python code structure. So I'm creating this issue to know if you're open to a huge python code cleaning:

- [x] Delete `__pycache__` folder
- [x] Add setup.py file => you will be able to push this project to Pypi
- [x] Create a clean folder structure
- [ ] Add documentation
- [x] Use web framework to clean http code (flask/falcon/???)
- [ ] Add yaml support
- [x] Add pycodestyle/pylint tests
- [ ] Add some external dependencies to simplify the source code
- [x] Add some unit tests
- [ ] Replace all prints by logger

What do you think about this ?

**Comment by mariusmotea** [comment] 2018-06-16 15:35
Hi,
Is only one issue, i'm not really python expert, never did the things you mention. I start to play with python after i saw the mysql/php implementation drawbacks and when somebody suggeste in one issue to take in consideration the programming language replacement. Now because the number of lines is too big i start to perform some seggragation, but is not easy to do this with the functions that use the bridge_config dict. If you know how to clean my code i will be happy to merge your pull requests.

**Comment by titilambert** [comment] 2018-06-16 15:45
Thanks for your answer !
Sorry I was not clear, I can do that ! My question was more about are you opened to that kind of things ?
If yes, I can start a fork/branch and make some merge requests ;)

**Comment by mariusmotea** [comment] 2018-06-16 18:21
Yes, this will be an improvement for sure.

Marius.

**Comment by titilambert** [comment] 2018-06-17 20:49
@mariusmotea I would suggest split this repository in two repositories:
1. a Github repository with only the python source (with only the `BridgeEmulator` folder as root)
2. a Github repository with all the DIY source code
What do you think about ?

**Comment by titilambert** [comment] 2018-06-17 23:32
I see !
So I just changed the folder structure.
You can see it here: https://github.com/titilambert/diyHue
What do you think about this ?

**Comment by titilambert** [comment] 2018-06-20 12:12
@mariusmotea Hello, I started splitting the `HueEmulator3.py` file in the `huebridgeemulator` folder.
My main issue today is to understand how this is working to validating I didn't break anything

**Comment by mariusmotea** [comment] 2018-06-20 12:33
start HueEmulator3.py script manually, i believe there are some errors when you open this page.

**Comment by titilambert** [comment] 2018-06-20 16:54
What do yo mean "some errors" ?
In fact, I'm just wondering what I should get ? (my configuration is empty and I never used hueEmulator before )

**Comment by mariusmotea** [comment] 2018-06-20 16:56
Ohh. I was believed that your lights are not displayed. Is fine to not have any lights displayed if there are no lights/rooms.

Marius.

**Comment by titilambert** [comment] 2018-06-20 17:08
Perfect, How can I add my yeelight bulb ?

**Comment by mariusmotea** [comment] 2018-06-20 17:12
Enable lan mode on the bulb, i write how in wiki. Then once the bulb is connected to your wifi network perform a light search from hue application.

**Comment by titilambert** [comment] 2018-06-20 17:15
OK so, the bulb is configured correctly, but how i can perform a light search ? I don't see any button in the UI

**Comment by mariusmotea** [comment] 2018-06-20 17:15
You need the android/iphone hue application

**Comment by titilambert** [comment] 2018-06-20 17:16
ho !

**Comment by titilambert** [comment] 2018-06-20 17:43
How can I simulate a hue button click ? The hue app can not join because the button was never join ?

**Comment by mariusmotea** [comment] 2018-06-20 17:48
Access emulatorip/touchlink to allow 30seconds for apps to pair with the emulator

**Comment by titilambert** [comment] 2018-06-20 17:50
Where did you define this credentials ?

**Comment by juanesf** [comment] 2018-06-20 17:50
Example, in browser:
192.168.8.10/hue/linkbutton
Hue is the user and password

**Comment by titilambert** [comment] 2018-06-20 17:51
Perfect ! Thansk !

**Comment by titilambert** [comment] 2018-06-20 18:18
I can see yeelight bulb ! Now I will try to control it

**Comment by juanesf** [comment] 2018-06-20 18:21
Good luck

**Comment by titilambert** [comment] 2018-06-20 18:55
Success ! I can control my yeelight bulb

**Comment by juanesf** [comment] 2018-06-20 19:56
Yo tengo un fork con una rama llamada OpenWrt la cual funciona en lede 17.01 perfectamente en GL-MT300A

**Comment by titilambert** [comment] 2018-06-29 03:07
Hello ! I got yeelight and Hue working ! I don't anything else continue the development :/
I just put a small documentation here to test it: https://github.com/titilambert/diyHue#new-folder-structure
As you can see I try clean up this wonderful project by:
- Splitting the main file
- Create a cli
- Add some arguments to the cli
- Using hug (https://github.com/timothycrosley/hug) as Python http framework
- Starting to use class to represent lights
- Add tox for tests
- Add pylint/pycodestyle

What next:
- Continue convert other brand bulb to class (like yeelight and hue)
- Start using class to represent scene, group, sensor, ...
- Add unit tests
- Add code documetation

@mariusmotea What do you think about this ?
If you like this new structure, how do you want to proceed to do think huge change in the main repository ? 
- Working on 2 branches in the same time (split and non-split) until the split one is ready then apply all patches from the non-split to the split ?
- Any better idea ?

**Comment by mariusmotea** [comment] 2018-06-29 20:20
I'm in vacation a few days, but now i browse your code and looks much better than mine. I will perform a test when i will arrive home. I made a commit after you started to work on this project, it is included? It is related to sunrise and sunset calculations using the astral module for python.

**Comment by mariusmotea** [comment] 2018-06-29 20:28
@titilambert i don't want to look like i don't appreciate your effort and ask too much, but i want to ask you if you know how to create that dtls server with psk for Hue Entertainment in python. Currently i spent hard time with wolfssl library to create this service in C, but i don't have experience and i did not manage to have a successful compile.

**Comment by titilambert** [comment] 2018-06-29 20:36
Hello ! No worries ! I don't have any experience with dtls but I'm sure I can help you with that. I guess we can do it un python. I found this: https://gist.github.com/manuels/8852953

What do you want to priorized ? Refectoring or dtls ? I think we should complete the refactoring as soon as possible.

I don't know if I got your last commit, if not, I could try to port it to this new structure.

Let me know when you come back.

**Comment by mariusmotea** [comment] 2018-06-29 20:39
Let's finish the current migrations then we can focus more on dtls. There are some libraries in python, the problem is that non offer support for DTLS server with PSK and that rare cipher used by hue entertainment.

**Comment by juanesf** [comment] 2018-06-29 20:50
Yo sigo investigando sobre gnutls y python-gnutls

**Comment by mariusmotea** [comment] 2018-06-29 21:33
The examples from python-gnutls are not made with psk. The requirements for hue entertainment are:

> Only DTLS mode version 1.2 with Pre-Shared Key (PSK) Key exchange method with TLS_PSK_WITH_AES_128_GCM_SHA256 set as Cipher Suite is supported.

**Comment by titilambert** [comment] 2018-06-29 21:35
@mariusmotea Do you want to create a new branch in your repository where I could push my changes then, you will be able to push also in this branch ?

**Comment by mariusmotea** [comment] 2018-06-29 21:37
Yes please.

**Comment by titilambert** [comment] 2018-06-29 23:21
@mariusmotea could you create a new branch in your repo called "refactor" ?  will create a PR to this branch (including your last changes)

**Comment by titilambert** [comment] 2018-06-29 23:53
@mariusmotea I just applied your last patch (daylight sensor) to my branch.

**Comment by mariusmotea** [comment] 2018-06-30 09:15
@titilambert i create the new branch

**Comment by mariusmotea** [comment] 2018-06-30 09:15
@titilambert 
The branch is now created.

https://github.com/mariusmotea/diyHue/tree/refactor

Marius.

**Comment by titilambert** [comment] 2018-07-02 17:15
I think we should create a new class: Registry
The configuration is in fact a registry where groups/devices/sensors/... are registered and where theirs states are stored.
At the end of the refactoring we should (kind of) "never" edit directly the "config.json" dictionnary as we are doing today.

**Comment by mariusmotea** [comment] 2018-07-02 17:45
I start to test the installation. The first issue is the lack of https. On official page of hue api was announced that http is not considered legacy and the developers have one year to switch to https. Now both services are running on original hue bridge. Can we start a new thread for https with the certificate from this repo?

**Comment by titilambert** [comment] 2018-07-02 18:33
Hello ! Ho ! I didn't know that ! I would suggest to not handle https directly from your source code. It should be handled by a true http server like nginx.
Also you should NOT provide a certificate, this imply insecure https connection. We should provide command lines to generate the certificate or use a service like "let's encrypt" to get it.
At the end, we should use ngnix running in docker to handle https.
I will try to add this today.

**Comment by mariusmotea** [comment] 2018-07-03 07:32
Original Hue Bridge use nginx for https relay to http, but i try to keep this standalone and independent as much as possible. By providing the cert + key you are right, is insecure like http, but currently here we are. Original Hue Bridge generate a self signed certificate with serial number as CN (generated from mac address + 4 constant letters in the middle), but i doubt the applications check the CN as the ssl of this certificate will always fail. Hug don't support https to add it as second thread like i did?

**Comment by TopdRob** [comment] 2018-08-24 06:57
Hi the efforts from @titilambert looked very promising. Any progress on there, it's quiet for a while?

**Comment by cheesemarathon** [comment] 2018-08-29 15:25
I'm closing this as there is now an issue for each of the mentioned refactoring categories. Chat can happen in those or on slack. Feel free to open more issue for additional categories @titilambert

**Closed by cheesemarathon** 2018-08-29 15:25 UTC
