### ISSUE TITLE
Docker container support

### ISSUE THREAD

**Issue by stackErr-NameNotResolved** [mariusmotea/diyHue#242] opened 2018-05-31 08:56 UTC
It would be great if an official docker container would be published. This way it would be very easy and fast to deploy diyHue without polluting the deploy target.

**Comment by stackErr-NameNotResolved** [comment] 2018-05-31 08:59
I can look into creating a Docker image if this isn't done before.

**Comment by mariusmotea** [comment] 2018-05-31 09:28
Is not a bad idea. I'm experienced with docker and next time when i will have some free time i will build suck image.

**Comment by brianmaher84** [comment] 2018-06-01 17:48
I am doing some testing on a dockerfile I have made now.

So far I've the portal up and running.

Philip Hue app has recognised the portal which is exposed and I can view the portal in website and login.

Just testing to make sure everything works.

**Comment by brianmaher84** [comment] 2018-06-01 19:07
I uploaded the dockerfile code to git now:
https://github.com/brianmaher84/hue-emulator/

You can try it out, I'm having problems getting my Philip Hue Go to connect but it isn't on the supported list.

The Web UI seems to work okay and apps can find the Gateway from my Android device, just can't connect my lamp to the emulator yet.  Still trying to find out what the issue is.

**Comment by mariusmotea** [comment] 2018-06-01 19:17
What is the final size of the image?

In my test i made image based on official python repo, but i need a way to add nmap to this

```
FROM python:3

WORKDIR /opt/hue-emulator

RUN pip install --no-cache-dir requests ws4py

COPY cert.pem HueEmulator3.py coap-client-linux config.json ./

COPY ./web-ui/* ./web-ui/

COPY ./functions/* ./functions/

CMD [ "python", "./HueEmulator3.py" ]
```

Marius.

**Comment by mariusmotea** [comment] 2018-06-01 19:30
size is ok, don't know why default python image use 900MB.

**Comment by brianmaher84** [comment] 2018-06-01 19:38
Oh strange, maybe it is geared more for development.  The Debian one does not even come with vi out of the box.  I've only installed what was needed.  Probably Alpine or one of the others maybe smaller/better choice.

I just went with Debian as I thought it would be reliable.

**Comment by mariusmotea** [comment] 2018-06-01 19:42
I test stackErr-NameNotResolved suggestions and now the python image have 124MB from ~900MB. Maybe you can go forward from here:

```
FROM python:rc-alpine
WORKDIR /opt/hue-emulator
RUN pip install --no-cache-dir requests ws4py
RUN apk update && apk add nmap
COPY cert.pem HueEmulator3.py coap-client-linux config.json ./
COPY ./web-ui/* ./web-ui/
COPY ./functions/* ./functions/
CMD [ "python", "./HueEmulator3.py" ]
```
Port 1900udp, 443 and 80 /tcp must be forwarded. Also config.json file must be mounted from host to be sure we don't lose the configuration very easy.

**Comment by cheesemarathon** [comment] 2018-06-03 11:49
Is there a way to specify an alternate location for the config? It would make it easier to mount from the host.

**Comment by brianmaher84** [comment] 2018-06-06 22:52
I'll do some more work probably at the weekend on the docker file to see if I can get it better.  I'll have a think about how best to manage the config.json and report back when I'm happy with what I've got.  Maybe I can make the clone operation something that happens if you pass a docker arg so it won't bomb the config.

You can pull a file from a docker container so if you want to just back it up with a cron job for the moment, it would work.

docker cp <containerId>:/file/path/within/container /host/path/target

**Comment by cheesemarathon** [comment] 2018-06-07 10:41
I think I have a container working with the config mounted on the host machine. It's only 124MB which isn't bad. I had to change where the config was located so I made a fork of diyHue [here](https://github.com/cheesemarathon/diyHue) with my changes and the docker file. The image can be found on [docker hub](https://hub.docker.com/r/cheesemarathon/diyhue/) and run with the following command:

`docker run -d --name='diyHue' -p '1900:1900/udp' -p '443:443/tcp' -p '80:80/tcp' -v '/opt/hue-emulator/config/':'/mnt/hue-emulator/config/':'rw' cheesemarathon/diyHue`

This mounts the config in the /mnt/hue-emulator/config/ directory on the host. This image currently wont run on raspberry pi as it is not built for ARMv6.

**Comment by mariusmotea** [comment] 2018-06-07 11:57
I believe this will be the best way:

`docker run -d --name=diyHue -p 1900:1900/udp -p 443:443/tcp -p 80:80/tcp -v /path/to/config.json:/mnt/hue-emulator/config.json cheesemarathon/diyHue`

On entrypoint it will execute one script like: if /mnt/hue-emulator/config.json has 0 bytes it means the config file is empty so will not work. If this happen we must dump the default config.json from this repo to it and then start HueEmulator3.py process.

**Comment by cheesemarathon** [comment] 2018-06-07 12:48
This is sort of what I have done. Due to the fact that host mounts, mount over the top of the container path, files in mounts must be added after container creation. Therefore, when the container starts, it executes the startup.sh script. This checks to see if the config is present. If not it grabs the latest one from GitHub. If it is present, it leaves the existing one there. This runs at every startup giving the easy ability to recreate the config if the current one is corrupted by deleting the config and restarting the container. However, if you would rather mount the config directly, removing the need to change the config directory, then I can try that.

**Comment by cheesemarathon** [comment] 2018-07-16 15:22
@mariusmotea 
I have been thinking about what you said about running the container as:
```
docker run -d --name=diyHue -p 1900:1900/udp -p 443:443/tcp -p 80:80/tcp -v /path/to/config.json:/mnt/hue-emulator/config.json cheesemarathon/diyHue
```
With this the config.json file must be created on the host before stating the container. The reason for this is as follows:

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v will create the endpoint for you. It is always created as a directory.

Therefor I still think it is better to mount a directory on the host containing the config.json rather than trying to mount a file directly. I can mount /opt/hue-emulator but I think it would be better to have a separate folder for configs so that the user doesn't have such direct access to the more system critical files also contained in /opt/hue-emulator. So, what do you think?

**Comment by mariusmotea** [comment] 2018-07-16 15:49
My point of view was enterprise related, were nothing must be stored in containers because we can delete and recreate quick in case are not healthy (k8s), however in this case we can think different. Maybe we can mount a folder were backups will be dumped, but we need a way to have a quick backup/restore option.

**Comment by cheesemarathon** [comment] 2018-07-16 18:02
That's the great thing with mounting a directory from the host. The files in the mounted directory from the host will remain after container deletion. Therefore, the container can be removed and recreated with the exact same config from the host. The config will not be stored in the container, just accessed by the container. If the config backups are moved to a config directory, they will be accessible no matter the container state. As for quick backup/restore, because the config and backups are stored outside of the container, we can stop, delete and recreate containers without losing the config. I hope that helps answer some of your questions. I have noticed that diyHue sometimes creates config.json backups. Where is save directory for this backup set in the code? I'll create a fork with the necessary changes and build the docker containers from that to test them.

**Comment by cheesemarathon** [comment] 2018-07-17 11:45
@mariusmotea 
Ok, I forked the repo and moved the config.json to a config folder. From that I have then built two images. One for Raspberry Pi and one for x86 systems. 
Run x86 system:
`docker run -d --name "diyHue" -p '1900:1900/udp' -p '443:443/tcp' -p '80:80/tcp' -v '/mnt/hue-emulator/config/':'/opt/hue-emulator/config/':'rw' cheesemarathon/diyhue:latest`

Run raspberry pi:
`docker run -d --name "diyHueARM" -p '1901:1900/udp' -p '444:443/tcp' -p '81:80/tcp' -v '/mnt/hue-emulator/config/':'/opt/hue-emulator/config/':'rw' cheesemarathon/diyhue-arm:latest`

I have not tested every function of the images but they both startup without errors. Where is the directory for the automatic backups defined? I'll change that also in my fork so that backups can be accessed by the user.

**Comment by mariusmotea** [comment] 2018-07-17 12:24
I propose to keep the config.json in container and to create the folder `backup`. On every Sunday night the automatic backup must not write the configuration backup in /opt/hue-emulator but in /opt/hue-emulator/backup and on /save GET request we need to write a copy of config.json file also in backup folder. To do this is pretty easy. From host we will mount just this backup folder in case we really care to have backups (maybe some guys use just 3 lights and is more easy to start from scratch).  Now we may have the case when we lose the container but we have the backup folder stored on host. To restore the configuration there is no support in application, but we can start the container with additional mount point just for the file config.json. In the future i will add a new future to restore the configuration from webgui to eliminate this inconvenient.

**Comment by cheesemarathon** [comment] 2018-07-17 16:58
That makes a lot of sense to me. Users can use the docker copy command to restore config backups until something is added to the UI. Where is the backup location defined for the backup scripts? I'll then make the necessary changes to my fork and docker containers.

**Comment by cheesemarathon** [comment] 2018-07-19 12:30
@mariusmotea 
Ok, so in my fork I have changed line 182 in HueEmulator3.py from
``def saveConfig(filename='/opt/hue-emulator/config.json'):``
to
``def saveConfig(filename='/opt/hue-emulator/backup/config.json'):``

The command to run the containers would now be:
Run x86 system:
``docker run -d --name "diyHue" -p '1900:1900/udp' -p '443:443/tcp' -p '80:80/tcp' -v '/mnt/hue-emulator/backup/':'/opt/hue-emulator/backup/':'rw' cheesemarathon/diyhue:latest``

Run raspberry pi:
``docker run -d --name "diyHueARM" -p '1901:1900/udp' -p '444:443/tcp' -p '81:80/tcp' -v '/mnt/hue-emulator/backup/':'/opt/hue-emulator/backup/':'rw' cheesemarathon/diyhue-arm:latest``

The save function that runs by heading to ``https://[hue_emulator_ip]/save`` works as the backup can then be viewed in the mounted directory. Will the timed backups still function correctly with my change or will I need to make further changes?

**Comment by mariusmotea** [comment] 2018-07-19 20:49
```
def saveConfig(filename='/opt/hue-emulator/config.json'):
    with open(filename, 'w') as fp:
        json.dump(bridge_config, fp, sort_keys=True, indent=4, separators=(',', ': '))
    Popen(["cp", "config.json", "backup/"])
```
because we need to keep also the current config.json in original location for container stop/start
```
if (datetime.now().strftime("%H") == "23" and datetime.now().strftime("%A") == "Sunday"): #backup config every Sunday at 23:00:10
                saveConfig("backup/config-backup-" + datetime.now().strftime("%Y-%m-%d") + ".json")
```
backups need to go directly in backups folder

**Comment by cheesemarathon** [comment] 2018-07-20 07:43
Thanks for that @mariusmotea! I've made the changes in my fork and rebuilt the images. Feel free to give the images a test and see what you think.

**Comment by mariusmotea** [comment] 2018-07-24 09:34
Hi,

Please note that there are big changes in last days. Docker image start to be a better option now because extra dependency of nginx. I propose following changes:

 - `RUN pip install --no-cache-dir requests ws4py astral` to install python-astral package needed to sunrise/sunset calculation
 - `RUN apk update && apk add nmap nginx curl`to install also nginx and curl
 - add nginx config files for nginx
 - rename backup folder for external mount point to `export` because we need to backup not only the configuration now but also the certificates. The reason why we need to backup the https certificate is because hue app (and very likely more app because this is the recommendation from Philips) cache the certificate and in case this is changed the app will not connect anymore until the cache data will be cleared.
 - create entrypoint.sh bask script and set this as entrypoint in docker. This bash script need to start both nginx and HueEmulator3.py and to download with curl the certificates in case these are not already present in export folder (see easy_install.sh updated by me).

**Comment by mariusmotea** [comment] 2018-07-24 09:41
and one more thing, this entrypoint.sh script before to start HueEmulator3.py script need check check in export folder if there is a file config.json.restore . If this is present then it need to move this file in /opt/hue-emulator/config.json. This way we have an option to start a fresh container with existing configuration file.

**Comment by cheesemarathon** [comment] 2018-07-24 09:47
I had noticed the big changes and have already started making the required changes. I'll work on finish making the changes as you recommend.

**Comment by cheesemarathon** [comment] 2018-07-30 11:32
@mariusmotea 
In theory I have the raspberry pi image working with nginx now, however i'm having trouble discovering the hub with the latest code regardless of if it's in a docker container or not. I noticed you mentioned that you were nearly done with removing the need for nginx, so I will wait for that and then adjust the images to work with that. I'll do some further testing after that.

**Comment by mariusmotea** [comment] 2018-07-30 11:56
Please wait a little bit i believe the code is working fine but i need to perform one installation from scratch to be sure all functions are working like before.

**Comment by cheesemarathon** [comment] 2018-07-30 11:57
Yeh thats no problem :smile:

**Comment by cheesemarathon** [comment] 2018-08-06 13:52
@mariusmotea I have update the image again so that it uses the latest version of diyHue that removes the need for nginx. However, I still can't find the bridge in the app. There is no response in the logs to the search so I'm wondering if the requests are getting through to the container. What ports does diyHue now use so I can make sure the container is accessible on them?

**Comment by cheesemarathon** [comment] 2018-08-09 12:08
I also think there was an issue with getting the MAC address for certificate generation. I am now passing it as an environment variable on docker run to make sure the correct host MAC address is used.

**Comment by cheesemarathon** [comment] 2018-08-10 10:42
@mariusmotea Success! I have the raspberry pi image working! The key was to change it to a host network instead of a bridge! As I also said before, I am now passing the hosts MAC address as an environment variable so that the cert is generated correctly. I have the raspberry pi image working on my raspberry pi 3b+ If you have a different version of a pi let me know if it works still. Docker run command is bellow. Make sure to change the MAC address to that of your host. Im not sure if it will work with a wrong mac address. I havn't tested all the functions, but I can connect with the Hue app and add lights!

`docker run -d --name "diyHueARM" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e "MAC=FF:33:EE:22:DD:11" cheesemarathon/diyhue-arm:latest`

**Comment by cheesemarathon** [comment] 2018-08-10 11:53
@mariusmotea Just confirmed that the non arm image works as well when started in host mode!

**Comment by cheesemarathon** [comment] 2018-08-21 12:35
Docker images have been created. Can we close this @mariusmotea

**Comment by mariusmotea** [comment] 2018-08-21 13:05
Yes, now is solved

**Closed by mariusmotea** 2018-08-21 13:05 UTC
