### ISSUE TITLE
ikea tradfri rgcct

### ISSUE THREAD

**Issue by camatthew** [mariusmotea/diyHue#445] opened 2018-11-18 22:59 UTC
**Describe the bug**
When using a rgbcct strip hooked up to a ikea tradfri gateway, the white leds does nothing,

**To Reproduce**
1. Go to localhost
2. change the color temputure

**Expected behavior**
The lights show the white leds on when the color temputure is selected.
**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**

**Comment by mariusmotea** [comment] 2018-11-19 06:29
Hi,

I don't understand how you connect the rgbcct strip to Tradfri Gateway. What kind of strip is this?

**Comment by camatthew** [comment] 2018-11-19 12:36
gledopto controller with generic rgcct strip. It works with ikea applications.

**Comment by mariusmotea** [comment] 2018-11-19 14:50
i'm not sure if this can be considered a bug in hue emulator because Ikea tradfri exposed api is very limited and this my be a limitation. At the time when i add support for tradfri gateway it was possible to set just 3 color temperatures to tradfri CCT bulbs (despite the bulbs are ZigBee compatible and support) and for this reason i was forced to create condition to play with just 3 values:

```
elif key == "ct":
                    if value < 270:
                        payload["5706"] = "f5faf6"
                    elif value < 385:
                        payload["5706"] = "f1e0b5"
                    else:
                        payload["5706"] = "efd275"
```
I see just one quick and expensive option, buy the Raspbee module and decommission the Tradfri Gateway.

**Comment by camatthew** [comment] 2018-11-19 22:35
or seperate warm white and cold white into seperate one color bulbs. also changing temputure doesent activate white leds.

**Comment by mariusmotea** [comment] 2018-11-20 12:53
I don't know try first to see if is possible with [pytradfri](https://github.com/ggravlingen/pytradfri)

**Comment by cheesemarathon** [comment] 2018-11-29 13:35
Closing as the issue is a limitation of the Tradfri hub. Use the Raspbee module as a possible fix. If pytradfri offers a solution, reopen this issue.

**Closed by cheesemarathon** 2018-11-29 13:35 UTC
