### ISSUE TITLE
Can not add Zigbee devices with Raspbee module

### ISSUE THREAD

**Issue by jorisvanr** [mariusmotea/diyHue#406] opened 2018-10-08 18:47 UTC
When I follow [these](https://github.com/mariusmotea/diyHue/wiki/Raspbee-module) steps I get stuck at the point that says _"Click "Unlock Gateway" in the Deconz settings to allow hue emulator to register, then open http://{hue emulator ip}/deconz to automatically register the bridge emulator with Deconz. In order to configure IKEA switches you must first configure the rooms"_. When I go to [my-IP]/deconz I get the "ERR_EMPTY_RESPONSE" error. 

I can add and control lights / sensors via [my-IP]:8080. 

These are the logs:
2018-10-08 18:46:05,176 - root - DEBUG - b827eb1d5699
2018-10-08 18:46:05,183 - root - DEBUG - Config loaded
2018-10-08 18:46:05,186 - root - DEBUG - starting ssdp...
2018-10-08 18:46:05,187 - root - DEBUG - start ssdp broadcast
2018-10-08 18:46:05,190 - root - DEBUG - sync with lights
2018-10-08 18:46:05,238 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 84, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1572, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

2018-10-08 18:46:05,254 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=1 HTTP/1.1" 200 93
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1585, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

2018-10-08 18:46:05,266 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 18:46:05,281 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0017/rgb_cct/1 HTTP/1.1" 200 102
2018-10-08 18:46:05,355 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 18:46:05,371 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0014/rgbw/1 HTTP/1.1" 200 82
2018-10-08 18:46:05,381 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 18:46:05,394 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0015/rgb_cct/1 HTTP/1.1" 200 102
2018-10-08 18:46:05,404 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 18:46:05,417 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0013/rgbw/1 HTTP/1.1" 200 82
2018-10-08 18:46:05,427 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-08 18:46:05,447 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=2 HTTP/1.1" 200 96
2018-10-08 18:46:05,457 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 18:46:05,473 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0011/rgb_cct/1 HTTP/1.1" 200 84
2018-10-08 18:46:05,484 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208

**Comment by mariusmotea** [comment] 2018-10-08 19:19
Did you edit deconz systemd file? I believe the port conflict is made with deconz that by default run on port 80. After you perform the fix just restart deconz service. 

```
pi@raspberrypi:~ $ sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9002            0.0.0.0:*               LISTEN      357/python3         
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      30634/python3       
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      307/deCONZ          
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      307/deCONZ          
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      592/sshd            
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      30634/python3       
tcp6       0      0 :::22                   :::*                    LISTEN      592/sshd        ```
this is my netstat config. As you can see deconz run on port 8080 and 8081 and hue emulator (python3) run on 80 and 443.

**Comment by mariusmotea** [comment] 2018-10-08 19:30
Ahh, sorry, i'm very tired right now. I believe you start HueEmulator3.py script without to stop hue-emulator service. Just stop the service sudo systemctl stop hue-emulator and then start the script and provide here the output. I believe it can be generated by missing keys in deconz (modelid).

**Comment by jorisvanr** [comment] 2018-10-08 19:43
I believe I did! I just tried it again and this is what I get 

`2018-10-08 19:42:54,243 - root - DEBUG - b827eb1d5699
2018-10-08 19:42:54,250 - root - DEBUG - Config loaded
2018-10-08 19:42:54,254 - root - DEBUG - starting ssdp...
2018-10-08 19:42:54,255 - root - DEBUG - start ssdp broadcast
2018-10-08 19:42:54,257 - root - DEBUG - sync with lights
2018-10-08 19:42:54,291 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,295 - root - DEBUG - Starting httpd...
2018-10-08 19:42:54,300 - root - DEBUG - Starting ssl httpd...
2018-10-08 19:42:54,308 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0011/rgb_cct/1 HTTP/1.1" 200 84
2018-10-08 19:42:54,381 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,399 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0017/rgb_cct/1 HTTP/1.1" 200 102
2018-10-08 19:42:54,410 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,421 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0016/rgb_cct/1 HTTP/1.1" 200 101
2018-10-08 19:42:54,431 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,446 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0013/rgbw/1 HTTP/1.1" 200 82
2018-10-08 19:42:54,456 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,469 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0014/rgbw/1 HTTP/1.1" 200 82
2018-10-08 19:42:54,479 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-08 19:42:54,506 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=1 HTTP/1.1" 200 93
2018-10-08 19:42:54,516 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,530 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0012/rgbw/1 HTTP/1.1" 200 83
2018-10-08 19:42:54,539 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:42:54,552 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0015/rgb_cct/1 HTTP/1.1" 200 102
2018-10-08 19:42:54,565 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-08 19:42:54,581 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=2 HTTP/1.1" 200 96`

**Comment by jorisvanr** [comment] 2018-10-08 19:45
When I also run _sudo netstat -lntp_ I get this: 

`pi@raspberrypi:~ $ sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      577/sshd            
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      355/cupsd           
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      32634/python3       
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      32634/python3       
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      353/deCONZ          
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      353/deCONZ          
tcp6       0      0 :::22                   :::*                    LISTEN      577/sshd            
tcp6       0      0 ::1:631                 :::*                    LISTEN      355/cupsd  `

**Comment by mariusmotea** [comment] 2018-10-08 19:49
Need to see the error when you access /deconz

**Comment by jorisvanr** [comment] 2018-10-08 19:59
Apologies! Of course: 

2018-10-08 19:58:45,595 - root - DEBUG - b827eb1d5699
2018-10-08 19:58:45,603 - root - DEBUG - Config loaded
2018-10-08 19:58:45,606 - root - DEBUG - starting ssdp...
2018-10-08 19:58:45,607 - root - DEBUG - start ssdp broadcast
2018-10-08 19:58:45,610 - root - DEBUG - sync with lights
2018-10-08 19:58:45,641 - root - DEBUG - Starting httpd...
2018-10-08 19:58:45,645 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-08 19:58:45,651 - root - DEBUG - Starting ssl httpd...
2018-10-08 19:58:45,750 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=1 HTTP/1.1" 200 93
2018-10-08 19:58:45,760 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:45,777 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0013/rgbw/1 HTTP/1.1" 200 82
2018-10-08 19:58:45,849 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:45,865 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0017/rgb_cct/1 HTTP/1.1" 200 102
2018-10-08 19:58:45,875 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:45,893 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0012/rgbw/1 HTTP/1.1" 200 83
2018-10-08 19:58:45,903 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-08 19:58:45,940 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=2 HTTP/1.1" 200 96
2018-10-08 19:58:45,949 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:45,963 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0011/rgb_cct/1 HTTP/1.1" 200 84
2018-10-08 19:58:45,972 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:45,996 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0015/rgb_cct/1 HTTP/1.1" 200 102
2018-10-08 19:58:46,005 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:46,021 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0014/rgbw/1 HTTP/1.1" 200 82
2018-10-08 19:58:46,031 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-08 19:58:46,043 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0016/rgb_cct/1 HTTP/1.1" 200 101
2018-10-08 19:58:52,017 - root - DEBUG - Sending M-Search response to 192.168.178.207
192.168.178.207 - - [08/Oct/2018 19:58:52] "GET /deconz HTTP/1.1" 200 -
2018-10-08 19:58:52,830 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1
2018-10-08 19:58:52,836 - requests.packages.urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/config HTTP/1.1" 200 243
----------------------------------------
Exception happened during processing of request from ('192.168.178.207', 57749)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1210, in do_GET
    scanDeconz()
  File "./HueEmulator3.py", line 921, in scanDeconz
    bridge_config["deconz"]["websocketport"] = deconz_config["websocketport"]
KeyError: 'websocketport'
----------------------------------------
192.168.178.207 - - [08/Oct/2018 19:58:53] "GET /deconz HTTP/1.1" 200 -
2018-10-08 19:58:53,020 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1
2018-10-08 19:58:53,025 - requests.packages.urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/config HTTP/1.1" 200 243
----------------------------------------
Exception happened during processing of request from ('192.168.178.207', 57750)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1210, in do_GET
    scanDeconz()
  File "./HueEmulator3.py", line 921, in scanDeconz
    bridge_config["deconz"]["websocketport"] = deconz_config["websocketport"]
KeyError: 'websocketport'
----------------------------------------

**Comment by jorisvanr** [comment] 2018-10-08 20:02
Sorry, I have no idea why the font is huge all of a sudden :-/

**Comment by mariusmotea** [comment] 2018-10-08 20:20
What version of deconz are you using? Never faced this error. Maybe they removed websocket key in last version.

**Comment by jorisvanr** [comment] 2018-10-08 20:34
It is the latest version:

Vendor dresden elektronik
Product RaspBee
Version 2.05.39 / 22-9-2018
Firmware 26240500

**Comment by mariusmotea** [comment] 2018-10-09 14:18
I will try to upgrade deconz in my home. The problem is that i need to arrive home a little earlier because in case of issue i will remain in total dark and my wife will complain.

**Comment by mariusmotea** [comment] 2018-10-09 18:05
I update Deconz and Raspbee firmware and still cannot replicate your issue. Please perform the following test that will reveal the issue. Inside config.json you have the username provided by deconz for api communication ( config.json => "deconz" => "username")
ex mine:
```
        "username": "283145a4e198cc6535",
        "websocketport": 8081
```
once you have the username perform this command:
`curl "http://127.0.0.1:8080/api/283145a4e198cc6535/config"` (replace my username with your) and paste here the output.

**Comment by jorisvanr** [comment] 2018-10-09 18:55
This is what is returned: 

{"apiversion":"1.0.9","bridgeid":"00212EFFFF02458B","datastoreversion":"60","devicename":"RaspBee","factorynew":false,"mac":"b8:27:eb:1d:56:99","modelid":"deCONZ","name":"Raspbee","replacesbridgeid":null,"starterkitid":"","swversion":"2.5.39"}

An interesting thing is that in the config in my file it says websocketport 8080... Could that be it?

**Comment by jorisvanr** [comment] 2018-10-09 19:42
Reinstall by following the steps [here](https://github.com/mariusmotea/diyHue/wiki/Raspbee-module)? I did that yesterday but I can try again. I don't have that many lights so maybe reinstall DIY Hue completely?

**Comment by mariusmotea** [comment] 2018-10-09 19:46
Stop hue-emulator and remove /opt/hue-emulator compleatly, then deploy it again. Remember that deconz allow pairing after you enable this in gateway settings.

**Comment by jorisvanr** [comment] 2018-10-09 20:14
Ok I think I fucked it up. I sometimes find 2 bridges and sometimes none. Also, when I find one I can not connect using the official Hue app.. 

What is the best way to completely remove it? :(

**Comment by mariusmotea** [comment] 2018-10-09 20:17
hmm, you have two emulators? Maybe you did not put `upnp=0` to disable deconz broadcast in systemd file. Try this: wipe/reinstall hue app, then skip detection by clicking Help button and there you can put the ip of bridge you want to pair. In your case is the Raspberry ip.

**Comment by jorisvanr** [comment] 2018-10-09 20:37
Ok I think I have it up and running again. I now see and am able to control the Tradfri light! Yeeey! 

I'm now trying to get the motion sensor to work. It is visible in the app not responding yet.

**Comment by jorisvanr** [comment] 2018-10-10 06:48
I am using [this one](https://nl.aliexpress.com/item/Nieuwe-Bijgewerkte-Xiaomi-Aqara-Human-Body-Sensor-Smart-Lichaam-Beweging-Bewegingssensor-Zigbee-Verbinding-Mihome-App-Via/32863707345.html?spm=a2g0s.9042311.0.0.13f74c4dToApS6). I can see it respond on motion in the Phoscon app (at port 8080) but it does not update in the Hue app.

**Comment by mariusmotea** [comment] 2018-10-10 07:39
start the script manually again in debug mode and put here the output. Be aware that when you start the script the sensor may have the status `motion = true`, so you need to stay a while to have the sensors with status `motion = false` and tigger it with some motion. If the status `dark = false` it means there is too much light to perform some actions.

**Comment by jorisvanr** [comment] 2018-10-10 20:15
Ok! So this is the output

sudo ./HueEmulator3.py
2018-10-10 20:12:37,796 - root - DEBUG - b827eb1d5699
2018-10-10 20:12:37,805 - root - DEBUG - Config loaded
2018-10-10 20:12:37,839 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1
2018-10-10 20:12:37,847 - requests.packages.urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/config HTTP/1.1" 200 1891
2018-10-10 20:12:37,857 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1
2018-10-10 20:12:37,861 - requests.packages.urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/lights HTTP/1.1" 200 316
2018-10-10 20:12:37,871 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1
2018-10-10 20:12:37,876 - requests.packages.urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "GET /api/283145a4e198cc6535/sensors HTTP/1.1" 200 1729
2018-10-10 20:12:37,880 - root - DEBUG - Starting deconz websocket
2018-10-10 20:12:37,887 - root - DEBUG - starting ssdp...
2018-10-10 20:12:37,899 - root - DEBUG - start ssdp broadcast
2018-10-10 20:12:37,904 - root - DEBUG - sync with lights
2018-10-10 20:12:37,909 - root - DEBUG - Starting httpd...
2018-10-10 20:12:37,915 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:37,922 - root - DEBUG - Starting ssl httpd...
2018-10-10 20:12:37,956 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0011/rgb_cct/1 HTTP/1.1" 200 102
2018-10-10 20:12:38,033 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:38,046 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0015/rgb_cct/1 HTTP/1.1" 200 102
2018-10-10 20:12:38,056 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:38,078 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0016/rgb_cct/1 HTTP/1.1" 200 103
2018-10-10 20:12:38,093 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:38,111 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0013/rgbw/1 HTTP/1.1" 200 82
2018-10-10 20:12:38,114 - root - ERROR - light 13 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 754, in syncWithLights
    bridge_config["lights"][light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2018-10-10 20:12:38,125 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:38,142 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0014/rgbw/1 HTTP/1.1" 200 82
2018-10-10 20:12:38,146 - root - ERROR - light 14 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 754, in syncWithLights
    bridge_config["lights"][light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2018-10-10 20:12:38,154 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-10 20:12:38,167 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=1 HTTP/1.1" 200 93
2018-10-10 20:12:38,183 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:38,198 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0012/rgbw/1 HTTP/1.1" 200 83
2018-10-10 20:12:38,206 - root - ERROR - light 12 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 754, in syncWithLights
    bridge_config["lights"][light]["state"]["hue"] = light_data["hue"] * 180
KeyError: 'hue'
2018-10-10 20:12:38,214 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.95
2018-10-10 20:12:38,229 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.95:80 "GET /get?light=2 HTTP/1.1" 200 96
2018-10-10 20:12:38,238 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.178.208
2018-10-10 20:12:38,251 - requests.packages.urllib3.connectionpool - DEBUG - http://192.168.178.208:80 "GET /gateways/0x0017/rgb_cct/1 HTTP/1.1" 200 103
192.168.178.59 - - [10/Oct/2018 20:12:40] "GET /api/cfcf916a4eab2b122d829dbfdf75b6d1/lights HTTP/1.1" 200 -
2018-10-10 20:12:44,714 - root - DEBUG - Sending M-Search response to 192.168.178.234
2018-10-10 20:12:45,817 - root - DEBUG - Sending M-Search response to 192.168.178.25
2018-10-10 20:12:47,725 - root - DEBUG - {"e":"changed","id":"4","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2018-10-10T20:12:47","lightlevel":16233,"lux":42},"t":"event"}
2018-10-10 20:12:47,767 - root - DEBUG - {"e":"changed","id":"5","r":"sensors","state":{"lastupdated":"2018-10-10T20:12:47","presence":true},"t":"event"}

**Comment by jorisvanr** [comment] 2018-10-10 20:18
A more concrete test: pointing the sensor to a wall and after a while moving my hand in front of it gives the following log:

192.168.178.200 - - [10/Oct/2018 20:17:01] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
2018-10-10 20:17:02,380 - root - DEBUG - {"e":"changed","id":"5","r":"sensors","state":{"lastupdated":"2018-10-10T20:17:02","presence":false},"t":"event"}
192.168.178.200 - - [10/Oct/2018 20:17:11] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
2018-10-10 20:17:16,364 - root - DEBUG - {"e":"changed","id":"4","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2018-10-10T20:17:16","lightlevel":16233,"lux":42},"t":"event"}
2018-10-10 20:17:16,383 - root - DEBUG - {"e":"changed","id":"5","r":"sensors","state":{"lastupdated":"2018-10-10T20:17:16","presence":true},"t":"event"}

**Comment by mariusmotea** [comment] 2018-10-10 20:19
```
2018-10-10 20:12:47,725 - root - DEBUG - {"e":"changed","id":"4","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2018-10-10T20:12:47","lightlevel":16233,"lux":42},"t":"event"}
2018-10-10 20:12:47,767 - root - DEBUG - {"e":"changed","id":"5","r":"sensors","state":{"lastupdated":"2018-10-10T20:12:47","presence":true},"t":"event"}
```
so to have action it must be `"dark":true`

**Comment by mariusmotea** [comment] 2018-10-10 20:19
Did you configured the sensor in hue application?

**Comment by jorisvanr** [comment] 2018-10-10 20:27
Yes. It is configured in the hue app to turn on a scene when it is past 22:00 (now) and when its dark. I lowered the lights to test it. This is my output now:

`2018-10-10 20:25:36,545 - root - DEBUG - {"e":"changed","id":"4","r":"sensors","state":{"dark":true,"daylight":false,"lastupdated":"2018-10-10T20:25:36","lightlevel":4772,"lux":3},"t":"event"}
2018-10-10 20:25:36,563 - root - DEBUG - {"e":"changed","id":"5","r":"sensors","state":{"lastupdated":"2018-10-10T20:25:36","presence":true},"t":"event"}`

So it seems to work, although my hue app says the last motion is measured about an hour ago and did not update the scene when the motion was detected.

**Comment by mariusmotea** [comment] 2018-10-10 20:29
This is wired. I have no idea why the rules are not triggered. I propose to join slack for more interactive debugging.

**Comment by jorisvanr** [comment] 2018-10-10 20:32
There now :)

**Comment by cheesemarathon** [comment] 2018-10-11 12:13
Closing this as the issue is quite complicated so debugging is occurring on Slack

**Closed by cheesemarathon** 2018-10-11 12:13 UTC
