### ISSUE TITLE
WifiManager not working with WS2812B ino.

### ISSUE THREAD

**Issue by warfair1337** [mariusmotea/diyHue#47] opened 2017-09-10 03:16 UTC
Hi.

Got everything working with the HueEmulator, but experiencing an issue while testing the WS2812B LED-strip. After writing the ino-file to NodeMCU, it does not present "New Hue Light" SSID. I get the typical ESP_xxxxxx SSID which I can connect to, but no http-reply from 192.168.4.1. I get IP in the same subnet and I can also ping 192.168.4.1. 

Have tried multiple NodeMCU (different manufacturers), but always the same issue. Also tried different versions of WifiManager (v12, 11 and 10) as I suspected this might be the issue. Using latest version of Arduino IDE.

Any advice is welcome :-) 
Or does someone know how to hack it so I can manually input wifi-credentials instead of using WifiManager?

Thanks.

**Comment by kurniawan77** [comment] 2017-09-10 08:00
did you erase the esp before writing a new ino-file? 

`python esptool.py -p com6 erase_flash`

or

[ESP Flaash Tool](http://www.pratikpanda.com/completely-format-erase-esp8266-flash-memory/)

**Comment by mariusmotea** [comment] 2017-09-10 08:08
In the same time i was writing same solution, fortunately github has auto refresh.
If you want to put wifi credentials in code, remove wifi-manager library, and add this:

```
const char* ssid = "********";
const char* password = "********";
```
then under setup replace:

```
  WiFiManager wifiManager;
  wifiManager.autoConnect("New Hue Light");
```

with

```
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
```
Do you have any activity under leds? if yes, then maybe you used same board in the past and have some credentials saved in fs area, that are not erased when you flash new code.

**Comment by warfair1337** [comment] 2017-09-10 10:22
I always erase the flash using esptool.py. One of the NodeMCU's was virgin, new unopened packaging.
Another friend of mine also experienced the same issue using a NodeMCU. 

LEDs are red after flash usually. The new NodeMCU i tried always flashes green, even after erasing and reflashing.

Also have some new Wemos D1 laying around, will try with these. Thanks for update on the manual Wifi setup, will give this a shot. Reporting back later :)

**Comment by mariusmotea** [comment] 2017-09-10 10:50
One last suggestion: don't compile the code on windows. I had some issues on the past with some projects, on mac os and linux where working fine, while on windows with same libraries i had some issues. On my strips i use wemos d1 mini and on my rgb bulbs i use directly the esp-12s module flashed on NodeMCU v1 board. You can try to flash one example from wifi-manager project to see if the issue is still present.

**Comment by warfair1337** [comment] 2017-09-10 12:40
Same issues with the Wemos, and manual wifi setup also doesn't work. It still presents the ESP_xxxxxx SSID and keeps flashing green. I have tried to erase flash in every possible way, but no matter what the AP does not disappear. On multiple units.

A friend who I work with on this project is experiencing the exact same issues. Our setup is pretty much the same, using NodeMCU v1 or Wemos D1. We have no issues using these devices with other things like ESPEasy and custom built projects.

Also tried compiling with my Macbook, but the results are the same. Using one of the WifiManager examples works flawlessly.

Any specific library versions? Arduino IDE version? Tried replacing USB-cables and flashed/compiled on both Windows and Mac with same issues.

**Comment by mariusmotea** [comment] 2017-09-10 13:29
This is wired.
i'm using arduino 1.8.1, wifi-manager version 0.12.0 and NeoPixelBus version 2.2.7 (here i see there is an update that i don't apply, try to downgrade). Also, if you can try other other light project that use pwm to see if the issue is with NeoPixelBus library.

**Comment by erazor666** [comment] 2017-09-11 00:03
Hello,
I'm having the exact same problem. Brand new nodemcu out of the box, clean Arduino IDE 1.8.4, Only added esp8266 and the two needed libraries (WifiManager and NeopixelBus). No errors during compile. It starts up and is giving a red light across the WS2812b stripe. Wifi Shows up as FaryLink_xxxx and does never change to "New Hue Light". No response on 192.168.4.1.
I will try with the manaul settings now, tried earlier today with a recycled (erased flash) nodemcu.

**Comment by mariusmotea** [comment] 2017-09-11 06:42
Hi!
I have 4 brand new wemos d1 mini pro that i buy one month ago. I will install latest Arduino IDE for mac and flash one of them to test if i will have the same issue. Anyway very important detail with the name "FaryLink_xxxx", i guess this can help to debug the issue. I recommend to flash also another light project that don't use neopixel bus library (ex Generic_RGBW_Light). From where did you buy the esp8266 boards and when? Maybe there is a new chip revision.

**Comment by erazor666** [comment] 2017-09-11 07:27
I do a whole lot of flashing of espeasy. I've noticed when flashing dev11 at least, the nodemcu will show an accesspoint named FaryLink_xxxx for a little while then that vanishes and the expected EspEasy0 (i think it was the name of it, not important in this context). I can take pictures of the boards if you need. ( http://s.aliexpress.com/uMn2uIZv )

I seem to recall, if i use the ino unmodified (using wifi manager) it will show FaryLink_xxx and when remvoing wifi manager it will show ESP_xxx. I can double check this if its important. 

Only have these nodemcu modules at the moment, but i have wemos d1 mini arriving some day soon hopefully. I do have some esp01 modules that i could test with if its any help.

**Comment by warfair1337** [comment] 2017-09-11 07:31
That is great news. I will try again today with the updated code :-)

**Comment by mariusmotea** [comment] 2017-09-11 07:36
Please check now, this must be fixed in #49

**Comment by warfair1337** [comment] 2017-09-11 08:00
Just tested the updated code, and now it works like expected! New Hue Light SSID now appears.
Thanks for your help.

**Comment by mariusmotea** [comment] 2017-09-11 10:37
Good! Let me know if you face other issues.

**Closed by mariusmotea** 2017-09-11 10:37 UTC

**Comment by At-M** [comment] 2018-06-24 01:36
I just had the same problem occur to me (Wemos D1 Mini), but instead of showing another SSID Name, it didn't show anything.
I used your #issuecomment-328326832 fix and it worked though.
