### ISSUE TITLE
Amazon Echo

### ISSUE THREAD

**Issue by nogueira** [mariusmotea/diyHue#1] opened 2017-04-13 17:40 UTC
Is there any way to be discoverable by Amazon Echo?

**Comment by mariusmotea** [comment] 2017-04-13 18:16
I don't have any Amazon Echo device home to test. The only difference from original Hue Bridge is the lack of SSDP discover service. Can you see any requests in apache access log when you try to discover the bridge? mac/ip's are setup in bridge-config.php?  So far all Android applications that i use work also without SSDP.

**Comment by nogueira** [comment] 2017-04-13 19:10
I think it could be the lack of SSDP service. Even the Android official Hue app didn´t find it, I have to put the IP address

**Comment by mariusmotea** [comment] 2017-04-13 19:13
Ok, for the moment i will leave this issue opened because currently i work on switches development. Maybe somebody with more experience can provide a workaround here.

**Comment by mariusmotea** [comment] 2017-04-17 16:18
Hi,
i've uploaded a new python script that handle ssdp discover requests. With official application this is working fine. Please note that i update also a few php files, so in case of issues please update.

**Comment by TimTower01** [comment] 2017-08-21 20:13
Hey, i am pretty net to this project. I got the emulator working on my raspberry pi and connected an esp8266 with neopixels attached to it running your HueLedStrip sketch to the emulated bridge. Additionally i was successfully able to control the neopixels with the hue app. Unfortunately i wasn't able to get the bridge recognized by alexa. Is this because of the non presence of the "button" on the bridge and if so how can i add it or emulate it? I hope you can help me with getting this very cool emulator connected to my amazon echo dot.

**Comment by mariusmotea** [comment] 2017-08-21 20:24
Happy to see that somebody can test this with Alexa. The link button is always pressed on Bridge emulator, for this reason there is no physical button. If Alexa is asking to press the link button then the discover process was successful, but not completed at last steep and very likely we will able to fix. Please start manually HueEmulator.py script and paste here entire output generated by Alexa pairing process.

**Comment by TimTower01** [comment] 2017-08-21 20:32
Wow what a fast reply. Alexa asks you every time to press the bridgbutton regardless if a bridge exists in the network or not. This is a part of the default reply. The problem is that there isnt any output during the process of discorvering devices.

**Comment by TimTower01** [comment] 2017-08-21 20:52
Ok i maybe know the problem. From now on and this was new to me because i thought that philips hue is implemented into my amazon echo you need the phillips hue skill. And you can only activate this skill if you connect your amazon echo with your myhue account. to do this it is neccessary to pair your emulated bridge with your myhue account. and if i have read your readme correct this is not possible due to a private protocol. So until now no amazon echo support if i have understand everything correct.

**Comment by mariusmotea** [comment] 2017-08-21 21:30
i check other emulators like ha-bridge. I don't find any warnings with Alexa, just for Google Assistant:

> ISSUE: Google Home now seems to not support local connection to Philips Hue Hubs and requires that it connect to meethue.com. Since the ha-bridge only emulates the local API, and is not associated with Philips, this method will not work. If you have an older Google Home application, this may still work. YMMV.

Maybe you need to pair with an older application version?

**Comment by kurniawan77** [comment] 2017-08-21 21:42
Connect to meethue.com...? 
Sounds to me like https://www.meethue.com/api/nupnp

**Comment by TimTower01** [comment] 2017-08-21 22:20
I am sorry but i to not realy u derstand what you mean with "maybe you need
to pair with an older version". Can you explain this a little bit further
for me?

Am 21.08.2017 23:42 schrieb "kurniawan77" <notifications@github.com>:

**Comment by mariusmotea** [comment] 2017-08-21 22:27
i know that Philips ask 3rd party developers to switch to remote api, for this reason old apps may still be working for pair process (i read somewhere that Google Now is working this way). Please try to use the latest HueEmulator script version available in develop branch, it contain some changes at ssdp discover level.

**Comment by TimTower01** [comment] 2017-08-21 22:44
Thank you for tring to fix this bug/error. but unfortionaly i am still getting no output during the pairing process.

**Comment by mariusmotea** [comment] 2017-08-22 17:37
In your output i don't see anything coming from another device than your smartphone. Sniffing the traffic will not help because the traffic is https encrypted. I guess help can come just from one person with a real hue bridge that can perform reverse engineering of remote api. I guess this can be done with a proxy server that will log all activity, because there is the option to use proxy server. After this i can implement this remote api and emulator will work like a real hue bridge.

**Comment by TimTower01** [comment] 2017-08-22 17:42
Sniffing https encrypted traffic is not that hard if you have access to the
proxysettings of the device to sniff. Have you implemented the proxy
feature of the hue bridge in your emulator? If so it is no problem for me
to capture the packets unencrypted if you think it could be useful.

**Comment by mariusmotea** [comment] 2017-08-22 19:01
Not necessary to implement this on my emulator. On a real bridge need to be configured, but currently i don't have a real hue bridge.

**Comment by TimTower01** [comment] 2017-08-22 19:08
Urrrm i think you misunderstood me. I need the proxy feature to capture
encrypted https traffic. But maybe the problem is that amazons echo uses
the same discorvery method like the phillips hue app. If this is true it is
obvious why it wouldn't work. Because the app doesn't autodetect the bridge
until you say the app on wich ip adress it has to search exactly it doesnt
detect the bridge. And if you have to feed the ip adress manually to detect
the bridge it is impossible to detect it with an echo becausethere isn't a
way to tell alexa the ip of the bridge during the process of discovering
devices.

**Comment by mariusmotea** [comment] 2017-08-23 06:46
No, the hue app use ssdp protocol for discovery and is working fine. When you connect a real hue bridge to network it will connect to Philips cloud services and there will register the local ip and his serial number. When there is a request to https://www.meethue.com/api/nupnp that come from same public ip then it will be retrieved a json with private ip and serial. The communication protocol of the bridge with cloud services is unknown and for this reason i cannot implement it. If somebody can perform reverse engineering of this protocol, then i will be able to implement. The best way to do this is to configure the proxy option on the bridge and dump entire traffic.

**Comment by thehappydinoa** [comment] 2017-10-01 21:50
Please check my GitHub page for a tutorial making it possible to control any device with payload V3 from Alexa

**Comment by mariusmotea** [comment] 2017-10-02 08:40
@thehappydinoa  This is great news.  Did you tested the integration with this hue emulator or you just expect to work because is using hue api?

**Comment by thehappydinoa** [comment] 2017-10-02 19:25
@mariusmotea I have not tested it yet, but I would love it if you would fork my program and use integrated it

**Comment by mariusmotea** [comment] 2017-10-02 19:44
Be sure i will add you to contributors with url. Not understand what do you mean with "fork my program and use integrated it". I propose you to write a wiki page with url to your repo and i will publish it as there is big interest for Alexa integration.

Marius

**Comment by thehappydinoa** [comment] 2017-10-02 22:19
That sounds like a good idea

**Comment by thehappydinoa** [comment] 2017-10-04 13:39
@mariusmotea I have made the edits necessary, but I would love some help making it work with the lights. If you open HueEmulator.py and find the function AlexaHandler.on() could you place the code that makes self.light_id turn on? [My Fork](https://github.com/thehappydinoa/diyHue)

**Comment by mariusmotea** [comment] 2017-10-04 17:27
This is more complicated than i expected. Anyway to turn on/off the light you must call the function sendLightRequest(light, data)

light is the light id on bridge (number but type string)
data is dictionary {"on" : True} or {"on": False}

Is not possible to use the built in support? I believe Alexa know the hue api protocol, and the only issued is to discover the bridge emulator that is behave like an original one.

Marius.

**Comment by TimTower01** [comment] 2017-10-04 19:22
I am happy to test the new builds just give me instructions what i have to
do and i am trying to contribute the best i can

**Comment by mariusmotea** [comment] 2017-10-04 20:09
Hi @TimTower01 
I suppose you can clarify some aspects because for me is very wired that my emulator is not working with Alexa, despite @kurniawan77 helped me with wireshark dumps from original hue bridge in order to implement same broadcast messages. 
Moreover i fount there is one issue on [this project ](https://github.com/probonopd/ESP8266HueEmulator) that they made big progress in order to pair the emulator with Alexa and this is much future less than my emulator, it has implemented just a few options and use an old hue api version.

 - Is there any output from emulator when Alexa search for it (hope you use latest version)?
 - can you see sniff the network for UPNP data like kurniawan77 did here #23 ?

Marius.

**Comment by mariusmotea** [comment] 2017-10-05 09:37
@TimTower01 can you perform a test new, i just change something in HueEmulator.py. Doing some google searches i found Alexa send M-SEARCH queries with "ssdp:discover", my script was replying just to one with "ssdp:all" so this can be the main reason why it was not discovered by Alexa.
Marius.

**Comment by TimTower01** [comment] 2017-10-06 16:26
Ok thanks for the update information.
I am currently not at home but i will check it out tomorrow. Thanks for
trying to get this feature implemented.

~Tim

Am 05.10.2017 11:37 schrieb "Motea Marius" <notifications@github.com>:

@TimTower01 <https://github.com/timtower01> can you perform a test new, i
just change something in HueEmulator.py. Doing some google searches i found
Alexa send M-SEARCH queries with "ssdp:discover", my script was replying
just to one with "ssdp:all" so this can be the main reason why it was not
discovered by Alexa.
Marius.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mariusmotea/diyHue/issues/1#issuecomment-334413299>,
or mute
the thread

**Comment by TimTower01** [comment] 2017-10-09 16:24
Marius you are the best. It works!!! Flawless detection of the devices. Even the Bridge gets directly detected by the app. Only the wiki is not as good as it could be because it is easy to miss that nmap is needed. But otherwise - Great work !!!!
 ~Tim

**Comment by mariusmotea** [comment] 2017-10-10 12:13
Great news, i will close this issue now.

**Closed by mariusmotea** 2017-10-10 12:13 UTC

**Comment by finnbennet** [comment] 2017-11-03 18:23
How did you connect the Bridge to Amazon Echo? I activated the Alexa-skill, created an account and started the search but it did not find any bridges.

Finn

**Comment by shbatm** [comment] 2017-11-03 19:38
Mine did not get detected right away, I had to restart the HueEmulator.py and then Disable/Re-enable the Skill on Alexa, then it found the emulated bridge.

**Comment by finnbennet** [comment] 2017-11-03 20:18
I tried a lot, rebooting the pi, restarting alexa and so on. But it still does not detect the pi. By the way the hue app works great after manually typing in the ip.

Finn

**Comment by mariusmotea** [comment] 2017-11-03 20:23
I believe ssdp discover is not working. Do you use any services that use ssdp port ? If you start manually HueEmulator.py script do you see any errors related to ssdp?

**Comment by finnbennet** [comment] 2017-11-03 20:29
When I manually start the script, that shows up:
`pi@raspberrypi:~/diyHue/BridgeEmulator $ sudo python HueEmulator.py
Config loaded
starting ssdp...
start ssdp broadcast
Starting httpd...
192.168.2.106 - - [03/Nov/2017 21:27:19] "GET /description.xml HTTP/1.1" 200 -
`

**Comment by mariusmotea** [comment] 2017-11-03 20:34
If official android app don't detect automatically the emulator there is some networking issue at ssdp protocol. In my case on every test this is working with no issues.

**Comment by mariusmotea** [comment] 2017-11-03 20:38
i made a test right now with the android hue app and as you can see it was working ok:

```
pi@raspberrypi:~ $ sudo ./HueEmulator.py 
Config loaded
starting ssdp...
start ssdp broadcast
Starting httpd...
Sending M Search response
HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.10.200:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFEC76B26
ST: upnp:rootdevice
USN: uuid:2f402f80-da50-11e1-9b23-b827ebc76b26::upnp:rootdevice


HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.10.200:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFEC76B26
ST: uuid:2f402f80-da50-11e1-9b23-b827ebc76b26
USN: uuid:2f402f80-da50-11e1-9b23-b827ebc76b26


HTTP/1.1 200 OK
HOST: 239.255.255.250:1900
EXT:
CACHE-CONTROL: max-age=100
LOCATION: http://192.168.10.200:80/description.xml
SERVER: Linux/3.14.0 UPnP/1.0 IpBridge/1.20.0
hue-bridgeid: B827EBFFFEC76B26
ST: urn:schemas-upnp-org:device:basic:1
USN: uuid:2f402f80-da50-11e1-9b23-b827ebc76b26


192.168.10.15 - - [03/Nov/2017 22:36:39] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.10.15 - - [03/Nov/2017 22:36:39] "POST /api/ HTTP/1.1" 200 -
in post method
/api/
{"devicetype":"Hue 2#HTC One_M8"}
[
    {
        "success": {
            "username": "a7161538be80d40b3de98dece6e91f904dc96170"
        }
    }
]
192.168.10.15 - - [03/Nov/2017 22:36:39] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170 HTTP/1.1" 200 -
192.168.10.15 - - [03/Nov/2017 22:36:40] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170 HTTP/1.1" 200 -
192.168.10.15 - - [03/Nov/2017 22:36:40] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/config HTTP/1.1" 200 -
192.168.10.15 - - [03/Nov/2017 22:36:40] "GET /api/a7161538be80d40b3de98dece6e91f904dc96170/lights HTTP/1.1" 200 -
```

**Comment by mariusmotea** [comment] 2017-11-03 22:01
i don't have any Echo device to tell you exactly, but you are not on the correct path. You must not use Philips cloud services because these are working just with original Philips devices. There must be another way to detect the hue bridge locally, without to involve the cloud services.

Marius.

**Comment by finnbennet** [comment] 2017-11-03 22:36
@shbatm How did you connect the echo to the bridge?

**Comment by TimTower01** [comment] 2017-11-11 14:40
The skill is only activateable when you have a meethue.com account with a linked bridge whivh is not possible with the emulator. Just to the Smart Home section and the kick on add devices to start a scan ot say "Alexa search for devices." to start the process of discovering the bridge. This is the way that i used

**Comment by adyanth** [comment] 2018-10-07 07:45
Hey, any chance the Hue Bridge actually uses UPnP instead of the private API to find devices?
